Test

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -15,8 +15,8 @@ env:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
+
     services:
       postgres:
         image: postgres:15
@@ -24,40 +24,55 @@ jobs:
           POSTGRES_PASSWORD: postgrespassword
         ports:
           - 5432:5432
+
     strategy:
       max-parallel: 4
       matrix:
         python-version: ['3.11.2']
 
     steps:
-    - name: Sjekke PostgreSQL-versjon
-      run: |
-        until pg_isready; do
-          echo "Postgres er ikke klar"
-          sleep 1
-        done
-        echo "Postgres er klar"
+      - name: Vente til PostgreSQL er klar
+        run: |
+          until pg_isready; do
+            echo "Venter på PosgreSQL..."
+            sleep 1
+          done
+          echo "PostgreSQL er klar"
 
-        echo "Versjon i runner:"
-        psql --version
+      - name: Verifisere PostgreSQL-version
+        run: |
+          echo "PostgreSQL-versjon i runner:"
+          psql --version
 
-        echo "Bevis på at postgres ikke kjører i runner:"
-        systemctl status postgresql || true # || true for å fortsette runner selv om return code er nonzero
+          echo "Bevis på at PostgreSQL ikke kjører i runner:"
+          systemctl status postgresql || true  # Fortsett selv om return code er nonzero
 
-        echo "Versjon i service container:"
-        psql -c "SELECT version();"
+          echo "PostgreSQL-versjon i service container:"
+          PSQL_VERSION=$(psql -c "SELECT version();")
+          echo $PSQL_VERSION
 
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v3
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Installere dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-    - name: Kjøre tester
-      env:
-        DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
-      run: |
-        python manage.py test
+          EXPECTED_PSQL_VERSION="PostgreSQL 15"
+          if [[ $PSQL_VERSION =~ $EXPECTED_PSQL_VERSION ]]; then
+            echo "PostgreSQL-versjon er $EXPECTED_PSQL_VERSION"
+          else
+            echo "PostgreSQL-versjon er feil"
+            exit 1
+          fi
+
+      - name: Sette opp Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v3
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Installere dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+      - name: Kjøre Django-tester
+        env:
+          DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
+        run: python manage.py test
